# vim: fdm=marker

[bell]
color = "#dddddd"
duration = 200

[colors] # {{{
cursor = { cursor = "#dddddd", text = "#000000" }
draw_bold_text_with_bright_colors = true
primary = { background = "#000000", bright_foreground = "#dddddd", foreground = "#aeaeae" }
vi_mode_cursor = { cursor = "#dddddd", text = "#000000" }

[colors.bright]
black = "#4d4d4d"
red = "#bf6060"
green = "#60bf60"
yellow = "#ccc466"
blue = "#6070bf"
magenta = "#bf60bf"
cyan = "#60afbf"
white = "#dddddd"

[colors.normal]
black = "#050505"
red = "#bf4343"
green = "#43bf43"
yellow = "#db9c2e"
blue = "#4358bf"
magenta = "#bf43bf"
cyan = "#43abbf"
white = "#aeaeae"

# }}}

[env]
RUST_BACKTRACE = "full"

[font]
normal.family = "EnvyCodeR Nerd Font"
size = 11

[hints] # {{{
alphabet = "jfkdls;ahgurieowpqytmv,c.x/znbJFKDLS:AHGURIEOWPQYTMV<C>X?ZNB"

[[hints.enabled]]
binding = { key = "U", mods = "Control|Alt" }
command = "b"
hyperlinks = true
mouse.enabled = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘\\\\]+"

[[hints.enabled]]
action = "Copy"
binding = { key = "Y", mods = "Control|Alt" }
hyperlinks = true
mouse.enabled = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘\\\\]+"

[[hints.enabled]]
action = "Select"
binding = { key = "O", mods = "Control|Alt" }
regex = "\\S+"

[[hints.enabled]]
action = "MoveViModeCursor"
binding = { key = "L", mods = "Control|Alt" }
regex = ".*"

# }}}

[keyboard] # {{{
bindings = [

# Vi mode: Alt-J - 5 Down {{{
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
# }}}

# Vi mode: Alt-K - 5 Up {{{
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
# }}}

# Vi mode: Alt-L - 5 Right {{{
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
# }}}

# Vi mode: Alt-H - 5 Left {{{
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
# }}}

# Ctrl-Alt-[ - Enter/Exit Vi mode
{ mode = "~Search", mods = "Control|Alt", key = "LBracket", action = "ToggleViMode" },
{ mode = "Vi|~Search", mods = "Control|Alt", key = "LBracket", action = "ScrollToBottom" },

# Ctrl-[ - Exit Vi mode
{ mode = "Vi|~Search", mods = "Control", key = "LBracket", action = "ToggleViMode" },
{ mode = "Vi|~Search", mods = "Control", key = "LBracket", action = "ScrollToBottom" },

# Escape - Exit Vi mode
{ mode = "Vi|~Search", key = "Escape", action = "ToggleViMode" },
{ mode = "Vi|~Search", key = "Escape", action = "ScrollToBottom" },

# Q - Exit Vi mode
{ mode = "Vi|~Search", key = "Q", action = "ToggleViMode" },
{ mode = "Vi|~Search", key = "Q", action = "ScrollToBottom" },

# Ctrl-[ - Exit Search mode
{ mode = "Search", mods = "Control", key = "LBracket", action = "SearchCancel" },

# Font size
{ mods = "Control", key = "0", action = "ReceiveChar" },
{ mods = "Control", key = "=", action = "ResetFontSize" },
{ mods = "Control|Shift", key = "+", action = "IncreaseFontSize" },

# ----------------------------------------

{ mode = "~Vi|~Search", key = ".", mods = "Control|Alt", action = "ToggleViMode" },
{ mode = "~Vi|~Search", key = ".", mods = "Control|Alt", action = "High" },
{ mode = "~Search", key = ".", mods = "Control|Alt", action = "SearchForward" },

{ mode = "~Vi|~Search", key = ",", mods = "Control|Alt", action = "ToggleViMode" },
{ mode = "~Search", key = ",", mods = "Control|Alt", action = "SearchBackward" },

{ mode = "Vi|~Search", key = "Space", action = "ClearSelection" },

{ key = "N", mods = "Control|Alt", action = "CreateNewWindow" },

{ key = "P", mods = "Control|Alt", action = "Paste" },

]

# }}}

[mouse]
hide_when_typing = true

[scrolling]
history = 8192
multiplier = 5

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t‘’«»‚‛“”„‟‹›⹂"

[terminal]
osc52 = "CopyPaste"

[window]
dynamic_padding = true
padding = { x = 2, y = 2 }
