# vim: fdm=marker

[bell]
color = "#dddddd"
duration = 200

[colors] # {{{
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4d4d4d"
red = "#bf6060"
green = "#60bf60"
yellow = "#ccc466"
blue = "#6070bf"
magenta = "#bf60bf"
cyan = "#60afbf"
white = "#dddddd"

[colors.cursor]
cursor = "#dddddd"
text = "#000000"

#[colors.footer_bar]
#foreground =
#background =

#[colors.hints]
#start =
#end =

#[colors.line_indicator]
#foreground =
#background =

[colors.normal]
black = "#050505"
red = "#bf4343"
green = "#43bf43"
yellow = "#db9c2e"
blue = "#4358bf"
magenta = "#bf43bf"
cyan = "#43abbf"
white = "#aeaeae"

[colors.primary]
background = "#000000"
bright_foreground = "#dddddd"
foreground = "#aeaeae"

#[colors.search]
#matches =
#focused_match =

#[colors.selection]
#text =
#background =

[colors.vi_mode_cursor]
cursor = "#dddddd"
text = "#000000"

# }}}

[cursor]
blink_timeout = 2
style = { shape = "Beam", blinking = "On" }
thickness = 0.25
vi_mode_style = "Block"

[font]
#offset.y = -1
normal.family = "EnvyCodeR Nerd Font"
size = 12

[hints] # {{{

[[hints.enabled]]
action = "MoveViModeCursor"
binding = { key = "O", mods = "Control|Shift" }
#command = "xdg-open"
hyperlinks = true
mouse.enabled = true
persist = true
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘\\\\]+"

# }}}

[keyboard] # {{{
bindings = [

# Vi mode: Alt-J - 5 Down {{{
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
{ mode = "Vi|~Search", mods = "Alt", key = "J", action = "Down" },
# }}}

# Vi mode: Alt-K - 5 Up {{{
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
{ mode = "Vi|~Search", mods = "Alt", key = "K", action = "Up" },
# }}}

# Vi mode: Alt-L - 5 Right {{{
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
{ mode = "Vi|~Search", mods = "Alt", key = "L", action = "Right" },
# }}}

# Vi mode: Alt-H - 5 Left {{{
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
{ mode = "Vi|~Search", mods = "Alt", key = "H", action = "Left" },
# }}}

# Ctrl-Alt-[ - Enter/Exit Vi mode
{ mode = "~Search", mods = "Control|Alt", key = "LBracket", action = "ToggleViMode" },
{ mode = "Vi|~Search", mods = "Control|Alt", key = "LBracket", action = "ScrollToBottom" },

# Ctrl-[ - Exit Vi mode
{ mode = "Vi|~Search", mods = "Control", key = "LBracket", action = "ToggleViMode" },
{ mode = "Vi|~Search", mods = "Control", key = "LBracket", action = "ScrollToBottom" },

# Escape - Exit Vi mode
{ mode = "Vi|~Search", key = "Escape", action = "ToggleViMode" },
{ mode = "Vi|~Search", key = "Escape", action = "ScrollToBottom" },

# Q - Exit Vi mode
{ mode = "Vi|~Search", key = "Q", action = "ToggleViMode" },
{ mode = "Vi|~Search", key = "Q", action = "ScrollToBottom" },

# Ctrl-[ - Exit Search mode
{ mode = "Search", mods = "Control", key = "LBracket", action = "SearchCancel" },

# Font size
{ mods = "Control", key = "0", action = "ReceiveChar" },
{ mods = "Control", key = "=", action = "ResetFontSize" },
{ mods = "Control|Shift", key = "+", action = "IncreaseFontSize" },

# ----------------------------------------

{ mode = "Vi|~Search", key = "Space", action = "ClearSelection" },

]

# }}}

[mouse]
hide_when_typing = true

[scrolling]
history = 8192

[terminal]
osc52 = "CopyPaste"

[window.padding]
x = 2
y = 2
